### PR TITLE
WL-3728: Reminder email should come from meeting organiser

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Review by buckett — COMMENTED** [review]
I'm not sure that using the creator instead of one of the organisers if the right thing todo here. Probably best to have the discussion on the jira.

**Comment by lardo-de-arnaud** [comment]
It's definitely not the right thing.

Sent from my iPad

On 18 Oct 2016, at 10:13, Matthew Buckett <notifications@github.com<mailto:notifications@github.com>> wrote:

@buckett commented on this pull request.

I'm not sure that using the creator instead of one of the organisers if the right thing todo here. Probably best to have the discussion on the jira.

**Comment by nicholaswilson100** [comment]
The creator _is_ the what is chosen in the Organizer field.  Are you getting confused by the off-putting variable name?

**Comment by nicholaswilson100** [comment]
Adam: what makes you think it's definitely not the right thing?

**Comment by lardo-de-arnaud** [comment]
Why not get it on Jenkins then I'll test?

Had I been asked to sign off the work before reviewing took place, we wouldn't be having this conversation. Let's try to do more signing off in future!

Adam

Sent from my iPad

On 19 Oct 2016, at 10:10, Nick Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:

The creator is the what is chosen in the Organizer field. Are you getting confused by the off-putting variable name?

**Comment by nicholaswilson100** [comment]
The conversation here should be about the code.

**Comment by nicholaswilson100** [comment]
Adam asked this to be merged without further review.

**Comment by nicholaswilson100** [comment]
Yes more sign offs is a great idea!  Give me a shout when you're ready to do the next one.

**Comment by nicholaswilson100** [comment]
A sign off wouldn't have picked up on the fact that creatorUserId looks like it's not the meeting organizer so that's not really the issue here.  Sign offs are good for other reasons.

## 

Nick Wilson
Software Developer / Project Lead
Technology Enhanced Learning, Academic IT
IT Services, University of Oxford
13 Banbury Road, OX2 6NN
Tel: 01865 613716

**Pull request merged**
