### PR TITLE
WL-4643: Long lists of Favourite sites do not wrap in MSIE

### PR DESCRIPTION
**Pull request by nicholaswilson100**
This is a patch from Sakai.

### CODE REVIEW

**Comment by buckett** [comment]
Could we have a Sakai reference in this?

**Comment by nicholaswilson100** [comment]
Yup sorry the Sakai Jira is: https://jira.sakaiproject.org/browse/SAK-31731 and the PR is : https://github.com/sakaiproject/sakai/pull/3552

**Comment by buckett** [comment]
There maybe a better fix for this that Sakai will use to holding off on it.

**Comment by buckett** [comment]
There is a better(?) fix in Sakai now which we should go with instead of this one.

**Pull request closed without merging**
