### PR TITLE
WL-4504: LTI improvements to display Admin site in Department column

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Matthew don't merge this yet -  I've put it into Sign Off

**Comment by buckett** [comment]
I think there might have been a plan to just use the delegated access property and to have a listener that kept it in sync so we didn't need a code change in this area.

**Comment by lardo-de-arnaud** [comment]
Yes that was the plan

adam

**Comment by nicholaswilson100** [comment]
Ah

**Comment by buckett** [comment]
If we're going to have a listener then we should probably close this request.

**Comment by nicholaswilson100** [comment]
Can we keep it open and I'll change it?

## 

Nick Wilson
Software Developer / Project Lead
Technology Enhanced Learning, Academic IT
IT Services, University of Oxford
13 Banbury Road, OX2 6NN
Tel: 01865 613716

**Comment by buckett** [comment]
Sure.

**Review by buckett — CHANGES_REQUESTED** [review]
Should have a listener and on Site changes that sets the property so we can use the normal column.

**Pull request closed without merging**
