### PR TITLE
WL-4395

### PR DESCRIPTION
**Pull request by nicholaswilson100**
$ is not defined yet at this point so it was throwing NPE

### CODE REVIEW

**Comment by buckett** [comment]
I thought we were going to drop all the mobile stuff from signup in the 11 upgrade?

**Comment by nicholaswilson100** [comment]
really, didn't know.

**Comment by lardo-de-arnaud** [comment]
Yes I asked nick to back out the 3 Mox jiras that have been merged

sent from my phone

On 6 Jul 2016 11:54, Matthew Buckett notifications@github.com wrote:

I thought we were going to drop all the mobile stuff from signup in the 11 upgrade?

**Comment by nicholaswilson100** [comment]
This is to do with WL-4395 - location field not showing

**Comment by nicholaswilson100** [comment]
I've removed the mobile code and the location and category fields are now showing

**Comment by nicholaswilson100** [comment]
Adam: do you have the ids of the 3 Mox jiras at all that need backing out?

**Comment by buckett** [comment]
`git blame` will show you, or you can see it in github: https://github.com/ox-it/sakai/blame/1b65c7706a965c97aef931b50e302477a57f8a99/signup/tool/src/webapp/js/signupScript.js#L766

**Comment by lardo-de-arnaud** [comment]
Why was the Jquery reference different from sakai 11
I guess we must have introduced the error so it would be useful to know which was the JIRA wot done for it?

Adam

sent from my phone

On 6 Jul 2016 12:01, Nick Wilson notifications@github.com wrote:

This is to do with WL-4395 - location field not showing

**Comment by nicholaswilson100** [comment]
This and other code is being backed out in backing out WL-1221

**Pull request closed without merging**
