### PR TITLE
WL-4057 WL-4071: Put jgroups config back in

### PR DESCRIPTION
**Pull request by nicholaswilson100**
This is just putting back the jgroups code I took out for WL-4071.

### CODE REVIEW

**Comment by buckett** [comment]
But do we know why it caused Sakai to stop starting up?

**Comment by nicholaswilson100** [comment]
Do you mean WebLearn staging?  No, I'm not sure there's much more than what's on the Jira to go on.

**Comment by buckett** [comment]
With this code enabled we've had problems with Sakai refusing to startup, what I'm concerned about is that we add this code back in and then later on down the line (eg when a datacentre dies) Sakai refuses to startup.

**Comment by lardo-de-arnaud** [comment]
The Portal chat code is a shambles anyway. My plan was to turn portal chat on then have a play on staging, however, it does sound risky if we cannot pinpoint why JGroups is causing Sakai not to start.

**Pull request merged**
