### PR TITLE
WL-4760 WL-4690: attachment icon is teensey weensey

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by buckett** [comment]
Why this rather than making the `.attach` class a correct width?

**Comment by nicholaswilson100** [comment]
Yes I see what you mean.  The problem though was introduced by adding a max-width so the logical thing to do is to remove it.  Making a change somewhere else seems like avoiding the issue to me.

**Comment by nicholaswilson100** [comment]
That said, I'm not sure I'm completely happy with 4690 which has caused these Jiras: 4756, 4760, 4753.  Also, the Sakai community doesnt 'seem 100% happy: https://github.com/sakaiproject/sakai/pull/3623

**Comment by nicholaswilson100** [comment]
Maybe a better solution for 4690 would be to restrict the places where the img class is applied like ottenhoff was suggesting?  And for /access we can add a class for images ..What do you think?

**Comment by lardo-de-arnaud** [comment]
we cant retroactively change existing HTML pages. surely there's no issue at all with resizing on /access pages is there?

**Comment by nicholaswilson100** [comment]
Good point

**Pull request merged**
