### PR TITLE
WL-5303 Reduce upload limit in assignments

### PR DESCRIPTION
**Pull request by buckett**
Reduce the maximum upload limit in assignments so that we don't end up writing large files to the network filestore only to throw them away.

### CODE REVIEW

**Comment by buckett** [comment]
Can we hold off on merging this until it's been confirmed that this is ok to do.

**Comment by lardo-de-arnaud** [comment]
Who would the confirmation come from?

**Comment by buckett** [comment]
This is fine to be looked at now.

**Comment by buckett** [comment]
And merged if appropriate.

**Pull request merged**
