### PR TITLE
WL-4536 Buttons should inherit Sakai style

### PR DESCRIPTION
**Pull request by bbbbgarcia**

### CODE REVIEW

**Comment by buckett** [comment]
Why not just remove the code rather than comment out?

**Comment by bbbbgarcia** [comment]
That kind of (bad) practise is actually quite extended all around the Mneme code, I guess I just wanted to be respectful with the original mantainers with the code and follow that pattern...

**Comment by buckett** [comment]
The practice of commenting out code? I don't think that's something we want to continue as over time you just end up with more and more commented out and nobody knows why.

**Comment by bbbbgarcia** [comment]
Updated.

**Comment by buckett** [comment]
Magic, thanks.

**Pull request merged**
