### PR TITLE
WL-4409: None of the Lessons buttons wok

### PR DESCRIPTION
**Pull request by nicholaswilson100**
There were 2 errors here in show-page.js. One was that there were some missing closing braces for a window resize function.  The other change I made was removing an unneeded comma at the end of argument to a function.

### CODE REVIEW

**Comment by buckett** [comment]
Could you do this as 2 commits, one referencing WL-4020 one referencing LSNBLDR-542, that way it's easier to find all of a feature to contribute back.

**Comment by nicholaswilson100** [comment]
yarp

**Comment by nicholaswilson100** [comment]
Is that what you meant?

**Comment by buckett** [comment]
Magic, thanks.

**Pull request merged**
