### PR TITLE
WL-1409 Better OpenURL support in citations

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Bad merge

The Import to WebLearn liink wasn't importing citations.

### CODE REVIEW

**Comment by buckett** [comment]
This doesn't look like the right fix as don't you need the window name to have the citation list that you're importing to?

**Comment by nicholaswilson100** [comment]
It's the right fix in one sense in that it makes the Import to WebLearn work.

At the moment, the 'Import to WebLearn' link is getting set as, e.g., 'http://localhost:8080/sakai-citations-servlet/efe3de99-08d4-43d0-b91f-8591e4c5764fefe3de99-08d4-43d0-b91f-8591e4c5764f?rft_id=oxfaleph011277642' which is incorrect because it's including the uuid twice (which is "efe3de99-08d4-43d0-b91f-8591e4c5764f" here). It's including it once in the Java (above) and once in the JS. This is removing it from the Java as happens in wl-10

**Comment by buckett** [comment]
Cool, should the parameter just be dropped?

**Comment by nicholaswilson100** [comment]
I've added my reaction :)

And dropped the parameter. It's more of a change but cleaner.

**Pull request merged**
