### PR TITLE
WL-1293 display joinable sites in the list of subsites

### PR DESCRIPTION
**Pull request by bbbbgarcia**
Only for logged in users as specified by Adam

### CODE REVIEW

**Comment by buckett** [comment]
This doesn't look to be using the Oxford hierarchy.

**Comment by bbbbgarcia** [comment]
It doesn't need to, it just adds joinable sites as subsites for every site.

**Comment by buckett** [comment]
I think we just wanted the Oxford hierarchy to display subsites that a user didn't have access to but were joinable.

**Comment by buckett** [comment]
When the oxford hierarchy loads subsites at the moment it filters out sites you don't have permission to view but it should instead filter out sites that you don't have permission to view or permission to join.

**Comment by bbbbgarcia** [comment]
The end result is the same and this way seems clearer logic wise, plus we think it's more interesting (respecting your rule of no UI differences at all and within the same component) for users to see an ordered list of subsites and then the joinable ones, so they know more or less what to expect when accessing the link ('why this entry redirects me to a site but the very next link asks me to join?').

Anyway and all said, we'd need more info about how Oxford's hierarchy actually works to update it. Thought you just wanted the SubSiteViewImpl class to be modified?

**Pull request closed without merging**
