### PR TITLE
WL-4698: Surveys is not responsive

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Review by buckett — COMMENTED** [review]
Is there a reason for not putting the CSS in the evaluations .css file instead of directly inline in the code?

**Comment by nicholaswilson100** [comment]
No, I'll put it in the css - much better thanks

**Comment by nicholaswilson100** [comment]
Rebased and in stylesheet

**Comment by nicholaswilson100** [comment]
Matthew don't merge this yet -  I've put it into Sign Off

**Comment by buckett** [comment]
Ok to be merged?

**Comment by nicholaswilson100** [comment]
Yeah ok

**Pull request merged**
