### PR TITLE
WL-5343 Remove the need for a local maven repository.

### PR DESCRIPTION
**Pull request by buckett**
This pulls in the sub-tree merge of xcri4j and then most of the actual changes are in 2021.

### CODE REVIEW

**Comment by buckett** [comment]
@wl-jenkins  retest this please

**Comment by buckett** [comment]
@wl-jenkins retest this please

**Comment by buckett** [comment]
Ok, there's a problem with how the artifacts are being resolved with this, to fix it I think you need to run:

    find ~/.m2/repository -name _remote.repositories -exec rm -v {} \;

to get maven to no longer try to use maven-repo to resolve artifacts. I've done this on jenkins and will see if that fixes the build.

**Comment by buckett** [comment]
@wl-jenkins retest this please

**Comment by buckett** [comment]
And I think you also need to run:

    find ~/.m2/repository -name \*.lastUpdated -exec rm -v {} \;

**Comment by buckett** [comment]
@wl-jenkins retest this please

**Comment by buckett** [comment]
Ok all my initial guesses were wrong, this is all because maven on jenkins has been configured to use maven-repo.oucs as a proxy for all requests.
I've now disabled this and it should work.

**Comment by nicholaswilson100** [comment]
Was it a pain testing this or was it obvious the specific WebLearn functionality affected? Would Adam gain anything from knowing what you tested (I'm sure he'll ask anyway)?

**Pull request merged**
