### PR TITLE
WL-4702 Customise the colours on the calendar tool.

### PR DESCRIPTION
**Pull request by RebeccaMiller-Which**

### CODE REVIEW

**Review by buckett — APPROVED** [review]
Is this something that the standard skin should be doing? I don't think this matter too much but if it's easy maybe.

**Comment by lardo-de-arnaud** [comment]
Yes this should be contributed back. Does Rebecca need to make a change because of this?

adam

**Comment by buckett** [comment]
Branch has conflicts.

**Comment by buckett** [comment]
Does primary Sakai colour work for doing this?

**Comment by RebeccaMiller-Which** [comment]
I didn't think we were contributing this back hence the code is in Ox customisations.

We wanted to use the Oxford dark blue for calendar events, only one colour is used for the calendar - it is lightened using CSS therefore I needed more than a change of Sass variable.

**Comment by RebeccaMiller-Which** [comment]
Conflicts resolved.

**Pull request merged**
