### PR TITLE
WL-3317 Improvements to the login choice page.

### PR DESCRIPTION
**Pull request by RebeccaMiller-Which**

### CODE REVIEW

**Review by buckett — APPROVED** [review]
Hmm.... I understand why you're doing this as it styles the login page like the portal. For someone coming to thing it's a little strange through as the login pages aren't in the portal.

**Comment by lardo-de-arnaud** [comment]
Can you explain your second sentence?

Adam

Sent from my iPad

On 18 Oct 2016, at 10:22, Matthew Buckett <notifications@github.com<mailto:notifications@github.com>> wrote:

@buckett approved this pull request.

Hmm.... I understand why you're doing this as it styles the login page like the portal. For someone coming to thing it's a little strange through as the login pages aren't in the portal.

**Comment by buckett** [comment]
The login pages aren't part of the portal but here we're using portal specific styling to style them if someone then comes along and changes the styling you might expect that it's only going to change the portal, but it's actually going to affect other things.

**Comment by RebeccaMiller-Which** [comment]
The external login page CSS is also in the reference directory and I couldn't find any CSS in the login directory.
Is Sass going to be rolled out to all components eventually?

**Comment by buckett** [comment]
I think it's just a case of someone doing the work to convert it to SASS. It's probably because it's not turned on by default and so when the work to convert to SASS was done it was forgotten about.

**Pull request merged**
