### PR TITLE
WL-4724 Minor change to HTML tag following Sakai feedback.

### PR DESCRIPTION
**Pull request by RebeccaMiller-Which**

### CODE REVIEW

**Comment by buckett** [comment]
Err, doesn't merge cleanly.

**Comment by RebeccaMiller-Which** [comment]
I think that is because I added more calendar event types in a Jira (WL-544) that you subsequently merged to 11.x.  Not sure how I resolve this, ff the java file so that the extra event types are also in this commit?

**Comment by buckett** [comment]
Yep.

**Comment by RebeccaMiller-Which** [comment]
Hopefully ok now.

**Pull request merged**
