### PR TITLE
WL-4392: Make /site/portal 'redirect to' ':' site (in the hierarchy)

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
The previous logic for where to send the user was:  if we are not on a site (e.g., /portal), then, if the user is not logged in, send them to the gateway site, and if they are logged in then send them to My Workspace.

The current logic is now:    if we are not on a site, then, if the user is logged in or not, send them to the gateway site.

**Comment by buckett** [comment]
But doesn't this just put the user in the gateway site outside of the hierarchy?

**Comment by nicholaswilson100** [comment]
Yes you're right.  I've changed it so that if we are not on a site (e.g., /portal) and if the user is logged in, we send them to the gateway site, represented as ':'  I know this is hardcoded but as it's just one character and it does all the work, i.e., keeps the URL of '/portal' but serves up the gateway site in the hierarchy I thought it was elegant.

**Comment by buckett** [comment]
I don't think this works for non logged in users though.

**Comment by nicholaswilson100** [comment]
Non logged in users get taken to the gateway site outside the hierarchy.  Should a non logged in user get to see the hierarchy? Obviously they shouldn't see the hierarchy site tools like Bring Site?

**Comment by buckett** [comment]
That's what happens on https://weblearn.ox.ac.uk/
They should see everything they have permission for shouldn't they?

**Comment by nicholaswilson100** [comment]
Ok.  I've changed it so it redirects to he gateway for non logged in users too.

**Pull request merged**
