### PR TITLE
WL-4717: Tutorial disappears off screen

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by buckett** [comment]
How is this related to WL-3318?

**Comment by nicholaswilson100** [comment]
Adam linked it (in the Jira) I think

**Comment by buckett** [comment]
But how is the code change related?

**Comment by nicholaswilson100** [comment]
The original Jira is SAK-25531

**Comment by buckett** [comment]
Is this a cherry-pick of changes on SAK-25531?

**Comment by nicholaswilson100** [comment]
No, it's not an issue on Sakai.

**Comment by buckett** [comment]
Why have a SAK reference on it then?

**Comment by nicholaswilson100** [comment]
Good point

**Comment by buckett** [comment]
So if it's not an issue on Sakai shouldn't it be related to one of our other changes?

**Comment by lardo-de-arnaud** [comment]
i believe this is either related to our custom top bar banner or possible the work rebecca did on some other area of the navigation

**Comment by buckett** [comment]
Would be good to know so when/if we contribute this back we don't introduce a bug in Sakai.

**Comment by lardo-de-arnaud** [comment]
i did make a comment on the WL ticket that if this was introduced via a local patch then we should include the fix with the original patch when we contribute back

**Comment by buckett** [comment]
This is caused by WL-4512 which put a `float: left` on the main body, this means that browsers think that our document is only 50px high which is why qtip pushes the items off the screen. I think we want to fix that issue as we will probably have other issues with modal dialogs that position incorrectly because of this.

**Comment by buckett** [comment]
Closing as I don't think we want this fix, please re-open if we do.

**Pull request closed without merging**
